### ISSUE TITLE
saveTo method has permission denied error on manjaro without webserver

### ISSUE THREAD

**Issue by madsalehi** [stechstudio/laravel-zipstream#100]
I'm using Laravel 10 and Manjaro OS without any webserver for my project
When i want to create a zip file with saveTo() method, it return this error:
mkdir: Permission denied

my code :

`
return Zip::create(time() . '.zip', $files) ->saveTo('/products/attachments/');`
            
i checked the permissions of the path and set 775 to it but error not fixed.

how can i fix that ?

**Comment by jszobody** [comment]
Is `/products/attachments/` really a root path on your server? That doesn't look right.

Perhaps you mean to use `storage_path()` along with that? I don't think you have a valid path.

Ultimately this package is using normal PHP filesystem methods for saving the zip. If it doesn't exist or isn't writeable, I can't help you. You'll need to do some troubleshooting of your own in PHP. Use the `is_writable()` method for example to see if PHP can write to the target path, once you've verified you have a valid, absolute path.
