### ISSUE TITLE
Update maennchen/zipstream-php package

### ISSUE THREAD

**Issue by LoganTFox** [stechstudio/laravel-zipstream#102]
https://github.com/stechstudio/laravel-zipstream/blob/c4f511615a9ff63934f21916c4eaedc7c8adb310/composer.json#L21

can we get this package upgraded to the latest version? I'm getting an error that would be resolved if it was requiring the latest version of this package.

```
  Problem 1
    - maennchen/zipstream-php[2.0.0, ..., 2.4.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - stechstudio/laravel-zipstream[4.12, ..., 4.13] require maennchen/zipstream-php ^v2.0 -> satisfiable by maennchen/zipstream-php[2.0.0, ..., 2.4.0].
    - Root composer.json requires stechstudio/laravel-zipstream ^4.12 -> satisfiable by stechstudio/laravel-zipstream[4.12, 4.13].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
composer [update stechstudio/laravel-zipstream] failed, composer command failed: exit status 2. stderr=
```

**Comment by jszobody** [comment]
Hi @LoganTFox. The latest version of `maennchen/zipstream-php` is going to require a rewrite of this package, as the architecture has changed dramatically. It's not a small task.

Do you know what else is trying to require `psr/http-message` version 2.0 in your composer.json file? That appears to be the conflict here, and might be resolvable.

**Comment by LoganTFox** [comment]
Thanks for pointing that out. It looks like my version of `guzzlehttp/guzzle:7.7` required `guzzlehttp/psr7:2.5.0` which requires `psr/http-message ^1.1 || ^2.0` I was able to downgrade to 1.1 and got it to install.
