### ISSUE TITLE
Compatibility with PHP 8.2

### ISSUE THREAD

**Issue by JshGrn** [stechstudio/laravel-zipstream#104]
Will there be many changes required for this compatibility requirement?

```
stechstudio/laravel-zipstream[1.0, ..., 1.7, 2.0, ..., 2.6.1, 3.0] require php ^7.1 -> your php version (8.2.11) does not satisfy that requirement.
```

**Comment by JshGrn** [comment]
Hmm, I didn't check the composer.json file before raising issue, it should install but perhaps its my composer version and it requires the double pipe?

https://github.com/composer/composer/issues/6755

**Comment by JshGrn** [comment]
Hmm, it was trying to install version 3, explicitly saying require 4.12 worked.

**Comment by mkraha** [comment]
How do you solved?
