### ISSUE TITLE
Always downloading as a html file with incorrect name

### ISSUE THREAD

**Issue by gally90** [stechstudio/laravel-zipstream#105]
I am adding 2 images as raw data to the Zip file & returning it. It returns a download named 5.html. When I rename the extension to .zip it opens perfect as a zip and all the files are there. I was wondering if anyone could help with this issue?

`return Zip::create('QRAssets.zip')->addRaw($png, 'QRPNG.png')->addRaw($promo, 'QRPromo.png');`

**Comment by jszobody** [comment]
Are you returning this from a normal controller method?

**Comment by gally90** [comment]
Yeah, it is being returned from a standard Laravel controller.

**Comment by jszobody** [comment]
I just stuck this in my routes web.php file:

```
Route::get('test', function () {
    return \Zip::create('QRAssets.zip')->addRaw(file_get_contents("/path/to/foo.png"), 'foo.png');
});
```

It worked as expected. I got a `QRAssets.zip` file with the PNG image inside.

Not sure what to tell you, I don't see an issue. I think you have something else going. If you are able to reproduce this issue with a fresh laravel app and just this download code, let me know. I'd be curious to see that if so.

**Comment by gally90** [comment]
Many thanks for the prompt replies & for your time taken to help. I shall try and figure it out!
