### ISSUE TITLE
Unable to install package.

### ISSUE THREAD

**Issue by younus93** [stechstudio/laravel-zipstream#106]
Hi, 
I am using laravel 9. When i try to install the package, i get the below error. 

`Problem 1
    - stechstudio/laravel-zipstream[1.0, ..., 1.7, 2.0, ..., 2.6.1, 3.0] require php ^7.1 -> your php version (8.1.2) does not satisfy that requirement.
    - stechstudio/laravel-zipstream[3.1, ..., 3.2, 4.0, ..., 4.5] require illuminate/support ^5.6|^6.0|^7.0|^8.0 -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - stechstudio/laravel-zipstream[dev-master, 4.6, ..., 4.13] require maennchen/zipstream-php ^v2.0 -> found maennchen/zipstream-php[2.0.0, ..., v2.x-dev] but the package is fixed to 3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires stechstudio/laravel-zipstream * -> satisfiable by stechstudio/laravel-zipstream[dev-master, 1.0, ..., 1.7, 2.0, ..., 2.6.1, 3.0, 3.1, 3.2, 4.0, ..., 4.13, 9999999-dev].`

**Comment by jszobody** [comment]
Do you have `maennchen/zipstream-php` already in your composer.json file? Error message sounds like you have that locked to a specific version, which conflicts.

**Comment by younus93** [comment]
Thanks for replying. 

No. I dont have that package. These are the packages I currently use. 

`"require": {
        "php": "^8.0.2",
        "asantibanez/livewire-calendar": "dev-master",
        "aws/aws-sdk-php": "^3.255",
        "calebporzio/sushi": "^2.4",
        "codeat3/blade-fluentui-system-icons": "^1.31",
        "codeat3/blade-iconpark": "^1.5",
        "filament/forms": "^2.0",
        "filament/tables": "^2.0",
        "guzzlehttp/guzzle": "^7.8",
        "laravel/framework": "^9.19",
        "laravel/jetstream": "^2.12",
        "laravel/sanctum": "^3.0",
        "laravel/scout": "^9.5",
        "laravel/tinker": "^2.7",
        "league/flysystem-aws-s3-v3": "^3.0",
        "league/flysystem-ftp": "^3.0",
        "livewire/livewire": "^2.5",
        "maatwebsite/excel": "^3.1",
        "power-components/livewire-powergrid": "^3.6",
        "sentry/sentry-laravel": "^3.1",
        "spatie/laravel-backup": "^8.1",
        "spatie/laravel-comments": "^1.4",
        "spatie/laravel-comments-livewire": "^1.2",
        "staudenmeir/laravel-adjacency-list": "^1.0",
        "te7a-houdini/laravel-trix": "^2.0",
        "teamtnt/laravel-scout-tntsearch-driver": "^12.1",
        "wire-elements/modal": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.7",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },`

**Comment by jszobody** [comment]
Strange. Your initial message that `maennchen/zipstream-php` is already fixed in your lockfile to version 3.1.0.

I have this package running in Laravel 9 in multiple apps successfully. There's just some issue with your composer.lock file that you'll need to sort out. Try running with the `-W` flag to update all dependencies. 

Make sure you're installing `^4.0` of this package as well.

**Comment by kletellier** [comment]
same issue for me, i've previously added package for aws s3, remove composer.lock and vendor folder and running composer update works fine

**Comment by younus93** [comment]
Any suggestion on how to make this package work?

**Comment by jszobody** [comment]
@goszowski The latest version of this package is 4.x, and supports PHP 8.x.

@younus93 Try removing the package and installing fresh, instead of upgrading. I have this package running successfully in Laravel 10 with PHP 8.3 apps.

@drjdr Yes I'm aware. `maennchen/zipstream-php` v3 was a major rewrite, requiring a pretty big rewrite of this package as well. It's on my list of things to work on, haven't been able to release it yet.

**Comment by jszobody** [comment]
@drjdr In case you haven't noticed, version 5 of this package was recently released based on `maennchen/zipstream-php` v3.1.
