### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by amit-zonvoir** [stechstudio/laravel-zipstream#112]
Problem 1
    - stechstudio/laravel-zipstream[1.0, ..., 1.7, 2.0, ..., 2.4] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.8] but it conflicts with your root composer.json require (^7.8).
    - stechstudio/laravel-zipstream 2.5 requires illuminate/support ^5.6|^6.0|^7.0 -> found illuminate/support[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - stechstudio/laravel-zipstream[2.6, ..., 2.6.1, 3.0, ..., 3.2, 4.0, ..., 4.5] require illuminate/support ^5.6|^6.0|^7.0|^8.0 -> found illuminate/support[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - stechstudio/laravel-zipstream[4.6, ..., 4.11] require illuminate/support ^5.6|^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - stechstudio/laravel-zipstream[4.12, ..., 4.14] require maennchen/zipstream-php ^v2.0 -> found maennchen/zipstream-php[2.0.0, ..., 2.4.0] but the package is fixed to 3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires stechstudio/laravel-zipstream * -> satisfiable by stechstudio/laravel-zipstream[1.0, ..., 1.7, 2.0, ..., 2.6.1, 3.0, 3.1, 3.2, 4.0, ..., 4.14].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require stechstudio/laravel-zipstream:*" to figure out if any version is installable, or "composer require stechstudio/laravel-zipstream:^2.1" if you know which you need.

**Comment by jszobody** [comment]
Your issue is that you have `maennchen/zipstream-php` locked at 3.1.0, but this package uses `maennchen/zipstream-php` version 2 currently. See #107.

If you are able to remove whatever else is locking `maennchen/zipstream-php` this package will work.
