### ISSUE TITLE
Zip fails when S3 links contains special characters 

### ISSUE THREAD

**Issue by Navjot-Sharma** [stechstudio/laravel-zipstream#2]
The zip streaming process fails when any of the s3 links contain special characters like '[' even though the file exists on S3.
Error:
Error executing "GetObject on "https://.." resulted in a `404 Not Found` response.

There is no such error if I use maennchen's ZipStream-PHP but I need to stream zip back to S3.

**Comment by jszobody** [comment]
Thanks. Fixed and verified.
