### ISSUE TITLE
EntityTooLarge (client): Your proposed upload exceeds the maximum allowed size 

### ISSUE THREAD

**Issue by Navjot-Sharma** [stechstudio/laravel-zipstream#20]
If zip size exceeds 5GB AWS S3 upload limit, then zip file uploading to s3 fails. It created a file of about 5.5GB in /tmp directory on local, but no any file was created on s3.

**Comment by jszobody** [comment]
I will put a note in the docs about this. S3 does limit an individual upload to 5GB, worth being aware of that if you're saving zips to S3 with this lib.
