### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by bakkertjebrood** [stechstudio/laravel-zipstream#25]
Great work! Can the package be used in Laravel 5.5?

**Comment by jszobody** [comment]
Not officially, no. We are requiring 5.6 or higher. You could try cloning this package, changing the composer.json to support 5.5 and give it a try. I have no idea if it will work, and we wouldn't be able to provide any support if you ran into issues.

Note that 5.5 is end of life this month, no one should be using it anymore if at all possible
