### ISSUE TITLE
Missing publish command in the documentation

### ISSUE THREAD

**Issue by khalyomede** [stechstudio/laravel-zipstream#32]
## Description

Trying to download files using the recommended setup code will produce an error (see this issue #24 for the log trace). The code assumes that some configuration are published, but the documentation misses from explaining this step.

## Expected result

- The documentation precise that we need to publish the configuration before using the package.
- After publishing the configuration, the minimal working code does not throw an error related to #24.

## Notes

I suggest to add this text before step 2. of the Quick Start section of the documentation:

_2. Publish the vendor configuration_

_In your terminal, go in your folder and run this artisan command to publish the config/zipstream.php file:_

```bash
php artisan vendor:publish --provider="STS\ZipStream\ZipStreamServiceProvider" --tag="config"
```

**Comment by jszobody** [comment]
If you continue reading #24 you'll see that you just need to run `php artisan config:clear`. 

The config does not need to be published. In fact, I discourage it unless you really need to make a change that isn't possible via ENV.
