### ISSUE TITLE
Wrong filename when used in Livewire

### ISSUE THREAD

**Issue by MannikJ** [stechstudio/laravel-zipstream#34]
Asking this question feels a bit stupid, but maybe you can still help me with my problem. 

I'm using code like the following to return a response from a Livewire action.

```php
$zip = Zip::create("tasks-{$ts}.zip");
foreach ($files as $files) {
    $zip->add($file->path, $file->name);
}
return $zip->response();
```

Everything works as expected except that the downloaded file has the wrong name. It is always called `download.txt`. So the name I pass to the Zip::create is completely ignored. 
I won't exclude that it comes from some code of my app, but I couldn't find anything yet.

**Comment by MannikJ** [comment]
I needed to overwrite the `content-disposition` header to make it work:
```php
$response = $zip->response();
$response->headers->set("content-disposition", "attachment; filename={$name}");
```

**Comment by jszobody** [comment]
Huh that's interesting, I haven't experienced this.

I'm setting the content-disposition here like this:

https://github.com/stechstudio/laravel-zipstream/blob/2c954316b91faaa5cacec214455dd9c6ac9ac3d5/src/ZipStream.php#L225

I haven't tried this with Livewire yet, I'll do that and see if I can reproduce.

**Comment by MannikJ** [comment]
Well, I have not gone on with my tinkering, because the overwrite solves my problem for now. But I guess it could really be a problem with how livewire processes and returns the response. I already checked and confirmed that content disposition header on the response instance was correctly set in the way you show above before it was returned from the action. So maybe livewire  can't handle the UTF-8 file name format your using.

**Comment by jszobody** [comment]
I recently had a chance to try this out in a Livewire app. The issue I ran into is that returning a binary response from a livewire method breaks the component, no javascript works after that. That's a livewire limitation, and not anything I can really fix.

It seems that the true answer here is to build a completely separate endpoint (non-livewire) that returns the zip stream, and link to that endpoint, rather than building the zip and returning directly from livewire. That's the answer I'm seeing in the livewire forms with other types of binary and redirect responses.

**Comment by jszobody** [comment]
@MannikJ I had the chance to play with this in a Livewire app recently. Confirmed the filename issue. While working on that though, I noticed that the entire contents of the Zip were being included, nested, inside the Livewire response payload.

In other words: it defeats the whole point of Zip streaming.

Even worse, the contents appear to be base64 encoded, meaning you send back a _much bigger_ Zip payload than needed.

All in all, I'd strongly recommend against trying to stream a Zip directly from a Livewire component method. Instead use a redirect, and have a dedicated route that returns a Zip stream. From what I can tell, that's the only way to get the benefits of streaming.

**Comment by cerulean-net** [comment]
@jszobody 
I'm facing the same issue, and trying to solve this with the dedicated route, which makes sense to me.
But what I'm not sure is how to pass the array of file paths to the route. It'd be great if I could have some hints.

**Comment by jszobody** [comment]
@cerulean-net

You want to store the details of your zip (database, cache, etc) with some unique ID, redirect to the dedicated route while passing in that ID, such that the dedicated route can retrieve the details (array of file paths) and build the zip. That's the high-level idea.

The easiest way I can think of would be to use cache and a random key:

```php
$temporaryID = Str::random();
Cache::put($temporaryID, $this->arrayOfFilePaths, now()->addMinute());
```

Now redirect to your dedicated route passing in `$temporaryID`. Your controller retrieves that from cache, and proceeds to build and return a ZipStream.

Make sense?

**Comment by cerulean-net** [comment]
@jszobody 
I had not come up with the cache idea. Now it works completely fine!
Thank you so much for your quick help.
