### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by affektde** [stechstudio/laravel-zipstream#35]
My question is, will this package also support PHP 8 in the future?

**Comment by jszobody** [comment]
Yes, it definitely will, I just haven't had time to test it out and verify there are no PHP 8 issues. If you happen to run the test suite successfully on PHP 8, let me know? Or better yet, submit a PR supporting PHP 8 in the composer.json file.

**Comment by michaeldnelson** [comment]
I've hacked in php8 support while waiting for an update.  I don't know enough about the project to feel confident this is production ready.  Here is a link to the diff if it is helpful.

https://github.com/stechstudio/laravel-zipstream/compare/master...michaeldnelson:php8-bridge

**Comment by introwit** [comment]
hi @jszobody any updates on this?

**Comment by jszobody** [comment]
@introwit I haven't been able to work on it myself. Have you tried this package on PHP8 yet?

@michaeldnelson Have you been using that fork on php8? If so, submit it as a PR. If tests pass I'll merge it.

**Comment by jszobody** [comment]
v3.1 is released with php8 support. Thanks all.

**Comment by michaeldnelson** [comment]
> @introwit I haven't been able to work on it myself. Have you tried this package on PHP8 yet?
> 
> @michaeldnelson Have you been using that fork on php8? If so, submit it as a PR. If tests pass I'll merge it.

Idk how I missed this, apologies.  Thanks for the update! @GITSKayDomrose @jszobody
