### ISSUE TITLE
I am getting error in window pc same code working in ubuntu( only in s3bucket zip normall zip is working )

### ISSUE THREAD

**Issue by jaydipsinhparmar** [stechstudio/laravel-zipstream#38]
I have getting error from STS\ZipStream\Exceptions\FilenameMissingException:  in file  for only window in xampp but it working in ubuntu. when zip create form s3bucket folder

STS\ZipStream\Exceptions\FilenameMissingException:  in file C:\xampp\htdocs\test\vendor\stechstudio\laravel-zipstream\src\Models\TempFile.php on line 20

#0 C:\xampp\htdocs\test\vendor\stechstudio\laravel-zipstream\src\Models\File.php(42): STS\ZipStream\Models\TempFile-&gt;getDefaultZipPath()
#1 C:\xampp\htdocs\test\vendor\stechstudio\laravel-zipstream\src\Models\File.php(66): STS\ZipStream\Models\File-&gt;__construct('C:\\xampp\\htdocs...', NULL)
#2 C:\xampp\htdocs\test\vendor\stechstudio\laravel-zipstream\src\ZipStream.php(289): STS\ZipStream\Models\File::make('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\test\app\Http\Controllers\API\PatientController.php(162): STS\ZipStream\ZipStream-&gt;saveTo('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\API\PatientController-&gt;downloadData(Object(Illuminate\Http\Request))
#5 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('downloadData', Array)
#6 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Route.php(239): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\API\PatientController), 'downloadData')
#7 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Route.php(196): Illuminate\Routing\Route-&gt;runController()
#8 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Router.php(685): Illuminate\Routing\Route-&gt;run()
#9 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#12 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), 600, '1')
#14 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#16 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Router.php(687): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#18 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#20 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Routing\Router.php(617): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\test\app\Http\Middleware\SetLanguage.php(40): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SetLanguage-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\xampp\htdocs\test\vendor\fruitcake\laravel-cors\src\HandleCors.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\test\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(140): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#39 C:\xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(109): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 C:\xampp\htdocs\test\public\index.php(55): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#41 {main}

**Comment by jszobody** [comment]
What version do you have installed? Please verify you are on version ^4.0 in your composer.json file. A previous version had issues with Windows paths and should be fixed.
