### ISSUE TITLE
ZipStream::create() should not be called statically

### ISSUE THREAD

**Issue by IstvanLovas** [stechstudio/laravel-zipstream#4]
Hi,

I am getting "Non-static method STS\ZipStream\ZipStream::create() should not be called statically" error message when i import the package via use STS\ZipStream\ZipStream;
when i import via use ZipStream I get "Class 'ZipStream' not found".

**Comment by jszobody** [comment]
What version of Laravel are you using?

**Comment by IstvanLovas** [comment]
I have just updated to Laravel 6

**Comment by jszobody** [comment]
I just updated the readme. The facade changed from `ZipStream` to just `Zip` last April, to avoid confusion with the ZipStream class (and the base ZipStream class we are using from `ZipStream-PHP`). I missed updating the docs back when that changed.

So:

```php
use Zip;

Zip::create(...);
```

That should work for you, let me know if it doesn't?

**Comment by IstvanLovas** [comment]
Awesome! It works like a charm.

Thank You so much for the quick response.
