### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by RSpeekenbrink** [stechstudio/laravel-zipstream#40]
When trying to save a zip to disk I get a failed to open stream: No such file or directory error.

To reproduce:

```php
$zipFIle = Zip::create('global.zip');

** add files **

$zipFile->save(storage_path('exports');
```

Laravel version: 8.27
PHP: 7.4

**Comment by RSpeekenbrink** [comment]
Nevermind, forgot this is a streaming library and the functions need to be chained. This works:

```php
$files = collect(.. add files ..);

 Zip::create('global.zip', $files)->saveTo(storage_path('exports'));
```

**Comment by RSpeekenbrink** [comment]
I thought I fixed it by chaining the functions, this is not the case.

**Comment by jszobody** [comment]
Does the `storage/exports` directory exist? If you've created the folder, it should write out the `global.zip` file there just fine.

**Comment by mbardelmeijer** [comment]
This seems to break the `saveTo` with the `s3://` prefix, as here the `registerStreamWrapper` hasn't been called yet. The following error it then triggered:

`is_dir(): Unable to find the wrapper "s3" - did you forget to enable it when you configured PHP?`

**Comment by TaylorFoster90** [comment]
@mbardelmeijer  I am getting this exact error, only on save. How can I get your fix into my project? I cam currently on version `"stechstudio/laravel-zipstream": "dev-master",`

**Comment by jszobody** [comment]
@TaylorFoster90 Are you attempting to save to a sub-directory path in S3? Does it work if you save to a root path with just a filename?

**Comment by jszobody** [comment]
@mbardelmeijer @TaylorFoster90 can one of you update `dev-master` and give it a try now? I believe I resolved that regression. I'll tag and release if you can confirm on your end.

**Comment by TaylorFoster90** [comment]
I was using sub directory but I made sure to create the dir before executing my zip scripts. I seem to have it working. What I had to do as a work around was:

```
use Aws\S3\S3Client;
. . . 
$client = S3Client::factory([
  'key'    => env('AWS_ACCESS_KEY_ID'),
  'secret' => env('AWS_SECRET_ACCESS_KEY'),
  'region' => env('AWS_DEFAULT_REGION'),
  'version' =>  "2006-03-01"
]);

$client->registerStreamWrapper();

$zip = Zip::create("test_zip.zip");

. . . // Add Some Files

$zip->saveTo("s3://cadi2-in-develop/departing_clients");
```

Registering that client was the only way for the save to work for me.

**Comment by jszobody** [comment]
Yup makes sense. That workaround should no longer be needed in latest `dev-master`, hoping you can confirm.

**Comment by TaylorFoster90** [comment]
@jszobody ill update package now and remove my workaround and report back.

**Comment by TaylorFoster90** [comment]
@jszobody Working after updating to latest. Ty!

**Comment by jszobody** [comment]
Awesome thanks for confirming. I just tagged v4.2 with this fix.

**Comment by mbardelmeijer** [comment]
Thanks @jszobody & @TaylorFoster90 💪
