### ISSUE TITLE
Missing example for files in DB

### ISSUE THREAD

**Issue by Dimonka2** [stechstudio/laravel-zipstream#42]
Hi, 
I am truing to figure out how to use your package in case the files are not stored on a disk.
Ideally it should look like following:

```php
return Zip::create("package.zip", function($zip) {
  // load data files in portions
  DataModel::chunk(200, function ($dataModels) use($zip) {
    foreach ($dataModels as $dataModel) {
        // add file from DB field to zip
        $zip->add($dataModel->dataField, $dataModel->fileName);
    }
  });
  return true; // all ok
});
```
so that you can really zip files on the fly.
Is this possible?

**Comment by jszobody** [comment]
How large of files are you storing in your database??

**Comment by jszobody** [comment]
This package expects any source to be able to provide a readable stream:

https://github.com/stechstudio/laravel-zipstream/blob/master/src/Models/File.php#L134

I'm not sure how to turn DB chunks into a stream, but if you can figure that out you can extend this File class and stream your database chunks directly to the zip and out to the user. In theory.

**Comment by Dimonka2** [comment]
I have resolved it using ZipStream directly:

```php
return response()->streamDownload(function () use($ids, $filename) {
                $options = new \ZipStream\Option\Archive();
                $options->setSendHttpHeaders(false);
                $zip = new \ZipStream\ZipStream($filename, $options);
                Media::whereIn('id', $ids)->select('id', 'original_name', 'data')->chunk(10, function($medias) use ($zip){
                    foreach ($medias as $media) {
                        $zip->addFile($media->original_name, $media->data);
                    }
                });
                $zip->finish();
            }, $filename);

```
