### ISSUE TITLE
is_dir(): Unable to find the wrapper &quot;s3&quot; - did you forget to enable it when you configured PHP?

### ISSUE THREAD

**Issue by kamran-ashlarglobal** [stechstudio/laravel-zipstream#44]
SaveTo() zip stream error. Same code working in local environment but when upload to the server and check it. it returns the error and not create the zip on s3 server. Please help me on this issue.

**Comment by kamran-ashlarglobal** [comment]
/vendor/stechstudio/laravel-zipstream/src/ZipStream.php:289

**Comment by jszobody** [comment]
You said it's working in your local environment, are you saving the file to s3 when running locally?

**Comment by kamran-ashlarglobal** [comment]
yes

**Comment by kamran-ashlarglobal** [comment]
Please provide solution on this as soon as possible.

**Comment by kamran-ashlarglobal** [comment]
even some other local environment have same issue getting same error is_dir()

**Comment by jszobody** [comment]
Please provide a short, concise reproducible example. I'm happy to help you troubleshoot, but I need some sample code, brief as possible, that causes this error for you.

**Comment by jszobody** [comment]
@kamran-ashlarglobal please upgrade to version 4.2 of this package, I believe it will solve the issue you are experiencing.

**Comment by kamran-ashlarglobal** [comment]
Thanks a lot its working now on server.
