### ISSUE TITLE
Filename is undefined and download does not start immediately

### ISSUE THREAD

**Issue by NKnuelle** [stechstudio/laravel-zipstream#45]
Hello,

first, thanks for this awesome library. It is exactly what I need right now.

The problem is: It does not work as expected. I am calling the Zip::create function in my controller like this:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Zip;

class DownloadController extends Controller
{
    public function getFileDownload(Request $request) {
        $filenames = $request->input('filenames');
        $mode = $request->input('mode');
        $username = $request->user()->getName();
        $filePaths = [];
        foreach($filenames as $filename) {
            array_push($filePaths, $this->getFilename($mode, $request->user()->getName(), $filename));
        }
        if ($filePaths) {
            return Zip::create("test.zip", $filePaths);
        }
        return response('Files not found', 404);
    }
}
```

On the client (latest stable Firefox and Chrome) no download is starting and the network activity shows a pending GET request to my API route. After a while a save Dialog appears which asks me to save a file called "undefined" declared application/octet-stream (1,1 GB) - Chrome downloads a "undefined.txt" instead. I expect that the download should start immediately (streamed download) and it should be of type zip - not octet-stream or txt, right?

If I download the file and rename it to .zip and I unzip it all files are there and everything works. The problem is that the streamed download, filename and content-type is not working as expected.

What can be the issue here?

**Comment by ambdisp** [comment]
Hi, I think I had similar problem, but it was request related. Are you using Axios lib?

**Comment by NKnuelle** [comment]
Yes I do. I think you're right. This is maybe client-related - not the server part.. 

I do the request like this (using Vuex):
```
download ({
    dispatch,
    commit,
    rootState,
    rootGetters
  }) {
    this.$axios({
      url: 'api/download',
      method: 'GET',
      responseType: 'blob',
      params: {
        filenames: rootGetters['files/getDownloadFilenames'],
        mode: rootState.config.mode
      } // important
    }).then((response) => {
      const url = window.URL.createObjectURL(new Blob([response.data]))
      const link = document.createElement('a')
      link.href = url
      console.log(response.headers)
      link.setAttribute('download', response.headers['content-disposition'].split('filename=')[1])
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    })
  }
}
```

I think the problem could be that I set the responseType to Blob and how I handle the download. Do you have an example how you accomplished this?

**Comment by ambdisp** [comment]
Have a look here
[https://gist.github.com/ambdisp/50a21039c08a18d4a350cf6da31c3312]()
Hope it helps.

**Comment by NKnuelle** [comment]
Hey @ambdisp,
no that does not not help. The problem still exists. I think axios is not able to accept streamed responses...

@stechstudio:
Is there any example using this library on the client?

**Comment by jszobody** [comment]
Yeah I think axios is waiting until it receives the full response before you see it as a browser download, which defeats the whole point of streaming.

My advice is to create a separate, dedicated endpoint in your Laravel app that streams out your zip, and in javascript you should _redirect_ to this endpoint. Let the browser hit it directly, and receive the stream directly.

Meanwhile the user will still stay on the original page, they won't actually see a redirect since it just prompts a download. Does that make sense?

**Comment by NKnuelle** [comment]
hey @jszobody 
could you post a small snippet how I can accomplish that? I am not sure if there is a way using JavaScript to redirect without changing the original page.

**Comment by jszobody** [comment]
window.location = '...'

**Comment by jszobody** [comment]
Your challenge is getting your list of filenames to the server. Of course you could serialize that list of filename (json? base64 encoded?) and pass it in directly:

`self.location = '/download?files=' + serializedFilenames;`

But that could turn out to be a very long URL, possibly prolematic. 

The other way I've handed this is two-step: have your ajax call still send the filenames to the server, only just have your server store those in DB or Cache and respond with an identifier. Not you can redirect to the download endpoint, passing in that identifier.

Also, if you have any trouble with `self.location = '...'` (which I've successfully used quite a bit) the other option is injecting a dedicated download frame. 

```
this.$axios({
      url: 'api/download',
      method: 'GET',
      params: {
        filenames: rootGetters['files/getDownloadFilenames'],
        mode: rootState.config.mode
      } 
    }).then((response) => {
      var downloadFrame = document.createElement("iframe");
      downloadFrame.setAttribute('src', '/download/' + response.identifier);
      downloadFrame.setAttribute('class', "downloadFrame");
      document.body.appendChild(downloadFrame);
    });
```

Something like that perhaps? I use this approach in one app where the user is repeatedly generating downloads from a dynamic list of files.

**Comment by NKnuelle** [comment]
Using self.location or navigating to the url manually is working as expected. The problem with that is, I can't use query params or anything like that as you already mentioned. So I will need to get my head around generating a temporary redirect url which will return the stream. But that's not easy at all..

**Comment by jszobody** [comment]
Sure, let me throw out some example code then for that.

Let's change your initial ajax endpoint to a `prepDownload` method, something like this:

```php
use Cache;
use Illuminate\Support\Str;

class DownloadController extends Controller
{
    public function prepDownload(Request $request)
    {
        $filenames = $request->input('filenames');
        $mode = $request->input('mode');
        $username = $request->user()->getName();
        $filePaths = [];
        foreach($filenames as $filename) {
            array_push($filePaths, $this->getFilename($mode, $request->user()->getName(), $filename));
        }
        
        if ($filePaths) {
            Cache::put($key = Str::random(), $filePaths, 300);
            return route('download', ['identifier' => $key]);
        }
        return response('Files not found', 404);
    }
}
```

This is pretty much your original function, only it stuffs the filepaths in Cache for 5 minutes and returns the full endpoint to a download route.

So then your same controller might have a second method:

```php
public function download($identifier)
{
    return Zip::create("test.zip", Cache::get($identifier));
}
```

Now you just need a route:
```
Route::get('/download/{identifier', [DownloadController::class, 'download'])->as('download');
```

And in your client-side code, after the ajax request, you can expect to receive back that URL endpoint from `prepDownload`, and you just need to redirect the user to it.

**Comment by NKnuelle** [comment]
Thank you very much.

This really works as expected. Currently I am thinking about security. My files should be only available to authenticated users. As far as I understand if the URL gets exposed the files would be exposed, too.

I would recommend to add a section into the readme of this library to give a small example of how to handle streaming downloads on the client. This would be very helpful for others, too I think.

**Comment by jszobody** [comment]
Great call, I'll try to do a write-up.

As for security, I would hope you can use normal Auth middleware and such to protect the route. You could also append the user's ID to the cache key to make sure no other user could access the same download:

```
$identifier = Str::random();
Cache::put($identifier . "-" . auth()->id(), $filePaths, 300);
return route('download', ['identifier' => $identifier]);
```

Then when retrieving from cache, append the user ID again:

```
return Zip::create("test.zip", Cache::get($identifier . "-" . auth()->id()));
```

Course there are lots of ways to skin this cat, that was just first that came to mind.

If you ensure the user is logged in AND that the cache key is unique just to them, you should be ok.
