### ISSUE TITLE
STS\ZipStream\Exceptions\FilenameMissingException

### ISSUE THREAD

**Issue by rickyanwar** [stechstudio/laravel-zipstream#47]
![image](https://user-images.githubusercontent.com/36995966/119821844-9b972080-bf25-11eb-9ac3-f424c9098d0b.png)
this my code,still got error `STS\ZipStream\Exceptions\FilenameMissingException` on laravel 6

I was change the file without whitespace I got error, how to use` storage::url `or `Storage `code

![image](https://user-images.githubusercontent.com/36995966/119823832-d4d09000-bf27-11eb-9ca9-56defee680b8.png)

**Comment by jszobody** [comment]
It's far better to load the file from your local disk path, not the URL. Something like...

```php
return Zip::create("package.zip", [
    storage_path("image_source/ssss_38_0.12154800 1622084372.jpg");
]);
```
