### ISSUE TITLE
Instructions for Livewire

### ISSUE THREAD

**Issue by ryangjchandler** [stechstudio/laravel-zipstream#49]
When working with Livewire, you're not able to return the `ZipStream` instance like you would in a controller. I believe that is down to Livewire not respecting the `Responsable` contract.

I then tried to return `$myZipInstance->response()` directly, but that also didn't work. The only way I could get it to work was by replicating the logic inside of `ZipStream::response()` using `response()->streamDownload()` instead:

```php
// Inside of a Livewire action.
return response()->streamDownload(function () use ($myZipInstance) {
    $myZipInstance->process();
}, $myZipInstance->getName());
``` 

I'm wondering whether this library should instead be using Laravel's own utilities for generating streamed downloaded instead of constructing the `StreamedResponse` instance manually.

**Comment by jszobody** [comment]
Yeah I still need to document how best to use this package with LW. 

The change you propose allows the LW response to work, however the Zip data gets buffered, base64 encoded, and included in the LW response to the browser. It defeats the whole purpose of zip streaming. 

The only true solution I know of right now is to have a separate, dedicated Laravel route/endpoint that returns the zip, and link to that outside of LW.
