### ISSUE TITLE
Add file from data

### ISSUE THREAD

**Issue by Firtzberg** [stechstudio/laravel-zipstream#5]
Hi, I'm trying to add a new file to the archive from raw data (string).
I tried using the addFile() method from the underlying ZipStream implementation, but when I do so nothing gets downloaded. The content is dumped to the browser window instead.
Here's a sample code.
```
use STS\ZipStream\ZipStreamFacade;

$zipStream = ZipStreamFacade::create('name.zip');
$zipStream->addFile('main.json', 'raw content');
return $zipStream;
```

**Comment by jszobody** [comment]
I just added support for raw file data and tagged version 1.6. Please update to this version and give it a try:

```php
use Zip;

return Zip::create("name.zip")
    ->add('raw content', 'foo.txt');
```

**Comment by Firtzberg** [comment]
Thank you!
This works.
