### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\stream_for() 

### ISSUE THREAD

**Issue by waelfawal** [stechstudio/laravel-zipstream#51]
i cant download return error 5 with this message Call to undefined function GuzzleHttp\Psr7\stream_for() 
[2021-07-06 15:13:06] local.ERROR: Call to undefined function GuzzleHttp\Psr7\stream_for() {"exception":"[object] (Error(code: 0): Call to undefined function GuzzleHttp\\Psr7\\stream_for() at D:\\Work\\medicaus\\QR-Pdf\\vendor\\stechstudio\\laravel-zipstream\\src\\ZipStream.php:274)
[stacktrace]
#0 D:\\Work\\medicaus\\QR-Pdf\\vendor\\stechstudio\\laravel-zipstream\\src\\ZipStream.php(308): STS\\ZipStream\\ZipStream->getOutputStream()
#1 D:\\Work\\medicaus\\QR-Pdf\\vendor\\maennchen\\zipstream-php\\src\\ZipStream.php(555): STS\\ZipStream\\ZipStream->send('PK\\x05\\x06\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00...')
#2 D:\\Work\\medicaus\\QR-Pdf\\vendor\\maennchen\\zipstream-php\\src\\ZipStream.php(375): ZipStream\\ZipStream->addCdrEof()
#3 D:\\Work\\medicaus\\QR-Pdf\\vendor\\stechstudio\\laravel-zipstream\\src\\ZipStream.php(172): ZipStream\\ZipStream->finish()
#4 D:\\Work\\medicaus\\QR-Pdf\\vendor\\stechstudio\\laravel-zipstream\\src\\ZipStream.php(204): STS\\ZipStream\\ZipStream->process()
#5 D:\\Work\\medicaus\\QR-Pdf\\vendor\\symfony\\http-foundation\\StreamedResponse.php(109): STS\\ZipStream\\ZipStream->STS\\ZipStream\\{closure}()
#6 D:\\Work\\medicaus\\QR-Pdf\\vendor\\symfony\\http-foundation\\Response.php(394): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()
#7 D:\\Work\\medicaus\\QR-Pdf\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\HigherOrderTapProxy.php(34): Symfony\\Component\\HttpFoundation\\Response->send()
#8 D:\\Work\\medicaus\\QR-Pdf\\public\\index.php(53): Illuminate\\Support\\HigherOrderTapProxy->__call('send', Array)
#9 D:\\Work\\medicaus\\QR-Pdf\\server.php(21): require_once('D:\\\\Work\\\\medicau...')
#10 {main}

**Comment by jszobody** [comment]
Huh. What version of Guzzle is installed? Just curious. The function is deprecated, but I don't think it has been removed yet.

**Comment by waelfawal** [comment]
![image](https://user-images.githubusercontent.com/24758169/124665582-8f539b00-deb5-11eb-8504-3df8217c42f3.png)

**Comment by jszobody** [comment]
Ok I just pushed an update on master that I think will resolve this. Can you temporarily set your version of laravel-zipstream to `dev-master` and composer update? Let me know if that fixes your issue. If it does, I'll tag a new release.

**Comment by waelfawal** [comment]
yes it fixed my issue, Thanks :D

**Comment by kw-pr** [comment]
FYI this is fixed in version `^4.4`
