### ISSUE TITLE
Cleanup after completion

### ISSUE THREAD

**Issue by ijaureguialzo** [stechstudio/laravel-zipstream#52]
Hello, 

I don't know if this is even possible/practical, but I'm using this library to stream a temporary folder and would like to delete that folder after completion and, as the `return Zip::create()` is the last command on the controller, I can't run anything else.

Would be possible to add a callback to the library so code can be executed after completion?

Something like this:

```php
return Zip::create("your_download.zip", $files)
    ->onCompletion(function () {
        Storage::disk('temp')->deleteDirectory($directory);
    });
```

Thanks!

**Comment by NicoHsu** [comment]
> Hello,
> 
> I don't know if this is even possible/practical, but I'm using this library to stream a temporary folder and would like to delete that folder after completion and, as the `return Zip::create()` is the last command on the controller, I can't run anything else.
> 
> Would be possible to add a callback to the library so code can be executed after completion?
> 
> Something like this:
> 
> ```
> return Zip::create("your_download.zip", $files)
>     ->onCompletion(function () {
>         Storage::disk('temp')->deleteDirectory($directory);
>     });
> ```
> 
> Thanks!

Maybe you can use "dispatch"?
It works for me to delete the temp folder.

```
dispatch(function () {
    // what you want to do
})->afterResponse();
```

**Comment by ijaureguialzo** [comment]
Il will try it, didn't know that existed... 

Thanks!

**Comment by ijaureguialzo** [comment]
Just for reference, I ended doing this:
```php
dispatch(function () use ($directorio) {
    Storage::disk('temp')->deleteDirectory($directorio);
})->afterResponse();
```
