### ISSUE TITLE
Save To Error

### ISSUE THREAD

**Issue by woserba** [stechstudio/laravel-zipstream#53]
Hi Sir, Good Day.
I got error when i want to save to in my storage folder.

STS\ZipStream\Exceptions\FilenameMissingException

Could you give me solution ?

Thank You Sir

**Comment by jszobody** [comment]
This usually means you are not passing a full, absolute path to the `saveTo` method.

If your path begins with a forward slash `/` or a windows drive letter path `C:\` you shouldn't get this error.

**Comment by woserba** [comment]
![image](https://user-images.githubusercontent.com/85057970/127868359-9215fa0f-e9f4-4966-9fa8-a70a881c4d95.png)

I use this path and check it with dd(public_path('storage\upload\shares\excelastana\\'.$date->format("d-m-Y"))); 

Could you help me Sir ?

**Comment by jszobody** [comment]
Do you want to _download_ the generated zip, or _save it_ to disk? 

If you want your user to download the Zip, don't use `saveTo` at all. Just return the `$zip` from your controller method and the zip file will be downloaded by your user.

**Comment by woserba** [comment]
no Sir, i want to save it to disk but check it if something wrong with my path but it can generate succesfully.
i don't know what is wrong.

**Comment by jszobody** [comment]
I'm not entirely sure, but I have a theory. I just pushed a small change.

Can you update your composer.json file to use `dev-master` for this package, and run `composer update stechstudio/laravel-zipstream` and then see if it works?

**Comment by woserba** [comment]
already try it Sir. Still got the same result.

**Comment by woserba** [comment]
Zip::create("package.zip", $array)->saveTo(public_path('storage\upload\shares\excelastana\\'));

**Comment by woserba** [comment]
that's is my zip code

**Comment by jszobody** [comment]
Wait that's your actual code? That shouldn't work at all. This is what a tinker session shows, just with your public_path:

```
>>> echo public_path('storage\upload\shares\excelastana\');
PHP Parse error: Syntax error, unexpected T_ENCAPSED_AND_WHITESPACE on line 1
```

You are escaping that final single quote. Remove the last backslash.

**Comment by woserba** [comment]
no, that's not show double backslash. it's disappear when i write in here.
i already to erase last backslash still got the same error.

**Comment by woserba** [comment]
Done Sir, Thank you for your fix 😄
