### ISSUE TITLE
filesize(): stat failed error

### ISSUE THREAD

**Issue by fotrino** [stechstudio/laravel-zipstream#54]
Hi everyone!
Thanks for this package! It works great.
However, I'm running into an issue while trying to test the package working within my application.

In order to test the zipping, I fake a file & test that it exists, which gives no error, but when i call Zip::create() i get the following error.

Greetings,
Facundo.

```php
it('can download all files', function () {
    UploadedFile::fake()->image('foo.jpg')->size(400)
        ->storeAs("{$this->job->folder_path}9.Issued Docs/", 'foo.jpg', [
            'disk' => 'jobs',
        ]);

    Storage::disk('jobs')->assertExists("{$this->job->folder_path}9.Issued Docs/foo.jpg");

    livewire(ListDownloadbleFiles::class, [
        'job' => $this->job,
        'user' => $this->user,
    ])
        ->call('downloadAll')
        ->assertDownload();
});

```

```php
  at vendor/stechstudio/laravel-zipstream/src/Models/LocalFile.php:15
     11▕      * @return int
     12▕      */
     13▕     public function calculateFilesize(): int
     14▕     {
  ➜  15▕         return filesize($this->getSource());
     16▕     }
     17▕ 
     18▕     /**
     19▕      * @return StreamInterface
```

**Comment by jszobody** [comment]
If you fake a file, it may only exist in Laravel's Storage mock, no? 

The code that you show failing is calling a PHP `filesize` function, which is expecting a real file on disk. If it's not there, this would be the expected error.

My advice would be to stick real files in /tmp for testing, that's how I do it at least.

**Comment by plompd** [comment]
Well, I use `Storage::url($model->file)` to get the real file that is actually on disk?

**Comment by jszobody** [comment]
Not sure what you mean. `Storage::url` generates an HTTP URL, not a local file path. You don't want to hand that to a Zip.

**Comment by plompd** [comment]
Ah, I see what you mean. (Laravel newbie here).
I thought that it would return a relative path to the file inside the storage. But I would need a physical path I guess?

**Comment by jszobody** [comment]
Yes you want a local `/tmp/filename.txt` type of path, with that filename.txt file really on disk at that location.

**Comment by jszobody** [comment]
See what `Storage::path` gives you. That should be the absolute path to the file on disk, if it really exists.

**Comment by plompd** [comment]
Results:

**Storage::path**
`D:\Laragon\www\qdportal\storage\app\ZsEpESwpwkbUP0L1u4u4Ehw7hEGxkQqW8MP908Wn.txt`

**Storage::url**
`/storage/ZsEpESwpwkbUP0L1u4u4Ehw7hEGxkQqW8MP908Wn.txt`

The file actually exists in that location. It is a local disk.

This is the stack: https://flareapp.io/share/Lm860ob7#F71

**Comment by plompd** [comment]
Thanks. I don't see the 4.5 tag. Is it hidden or something?
