### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by jaseyd** [stechstudio/laravel-zipstream#57]
Hi there, I can get this package writing to my local storage directory. This is great.

However, I'm trying to use it to write to Azure Blob Storage (using the package matthewbdaly/laravel-azure-storage).

Using the package mentioned, I have my Azure blob storage configured as a 'storage disk' in Laravel which I can write to using commands like `Storage::disk('azure')->put('example.txt', 'Contents');`

Do you know how I'd get this package to write the zip file output to this disk?

Kind regards
Jason

**Comment by jaseyd** [comment]
On further investigation, it seems this will not be possible. The alternative will be to write the files locally, then move them to azure blob storage.

This can be closed.

**Comment by kw-pr** [comment]
@jaseyd I know this is an old issue, but I have the same problem right now. Do you remember why this is not possible?

Looks like this can be done with [C#](https://stackoverflow.com/a/20566524/956397).

Did you use the REST API?

Shouldn't it be possible to just add a HTTP file sources?

    Zip::create("package.zip")
        ->add("https://...", "myfile.pdf");
