### ISSUE TITLE
utf-8 unicode file name img_১০০৩৯৬৭_65464.jpg 

### ISSUE THREAD

**Issue by studentmanik** [stechstudio/laravel-zipstream#59]
img_**১০০৩৯৬৭**_65464.jpg 

STS\\ZipStream\\Exceptions\\FilenameMissingException(code: 0):  at /vendor/stechstudio/laravel-zipstream/src/Models/TempFile.php:20

**Comment by jszobody** [comment]
Not sure I understand. Can you explain what you're doing when you get this error? `FilenameMissingException` usually means that you're attempting to zip a file that can't be found. 

Perhaps some example code would help?
