### ISSUE TITLE
v1.6 FilenameMissingException error?

### ISSUE THREAD

**Issue by it-can** [stechstudio/laravel-zipstream#6]
Since 1.6 I get this error

```
STS\ZipStream\Exceptions\FilenameMissingException
```

my code:

```
$files = [
'/tmp/test.pdf',
'/tmp/test2.pdf',
];

// Zip it
        Zip::create('file.zip', $files)
            ->saveTo(storage_path('app/tmp'));
```

on 1.5 it works

**Comment by jszobody** [comment]
That means those files don't exist on disk, or aren't readable. Double check that `/tmp/test.pdf` and `/tmp/test2.pdf` are present with proper permissions?

In v1.6 we introduced the ability to create a zip entry from raw data. At the moment you can see the logic used to determine whether a filepath on disk was provided, and if it's not a valid path we assume it's raw data instead:

https://github.com/stechstudio/laravel-zipstream/blob/030a943679e6983c8d06791e9b70ac7d943fbfee/src/Models/File.php#L55-L59

The exception you're getting means the above check did not find a valid file on disk, assumed it was raw file data, and passing raw data absolutely requires providing an explicit filename with extension.

Hope that helps, let me know if that doesn't solve the issue.

**Comment by it-can** [comment]
Files are in place (1.5 works normally)

**Comment by it-can** [comment]
I double checked, all files exist and still getting this error.


also is this function correct? it returns the filename of the file not a path?
```
/**
     * @return string
     */
    protected function getDefaultZipPath()
    {
        return basename($this->getSource());
    }
```

**Comment by it-can** [comment]
Mmm seems that the code wants to "add" the zipfile to the archive?

```
$files = [
'/tmp/test.pdf',
'/tmp/test2.pdf',
];

// Zip it
        Zip::create('file.zip', $files)
            ->saveTo(storage_path('app/tmp'));
```

This will add, test.pdf, test2.pdf and file.zip to the archive. So file.zip does not exists and tries to add it as a tempfile... Thats giving the error...

**Comment by it-can** [comment]
@jszobody

**Comment by jszobody** [comment]
Ok the issue was the `saveTo`, I had been focusing on the source files. 

It's fixed, with a test case specifically setup for your scenario:

https://github.com/stechstudio/laravel-zipstream/blob/61d048240b62e3ff78dec01d5c58d060aa23a1cc/tests/ZipTest.php#L25-L36'

Version 1.7 is released with this fix.

**Comment by it-can** [comment]
Thanks!!
