### ISSUE TITLE
What about private files?

### ISSUE THREAD

**Issue by artjomzab** [stechstudio/laravel-zipstream#60]
Hello,

I have some files stored in `private/` instead of `public/`. This is how I store them:

    Storage::put($fileName, $content, 'private');

When I run:

```
$files = collect(Storage::files("/private/{$this->user->id}/backups/backup_{$this->user->backup->id}/"))
            ->map(fn($file) => Storage::path($file)) // get the absolute path
            ->toArray();

return Zip::create("backup.zip", $files);
```

I get:

> fopen(/var/www/html/storage/app/private/1/backups/backup_955ef575-ba3f-42ee-a1da-4efaa87edca2/10414.pdf): Failed to open stream: Permission denied

![Screenshot 2022-01-16 185443](https://user-images.githubusercontent.com/524580/149671803-b6a9996e-ef6c-4b53-92bb-785e7c52aa58.jpg)

I am using laravel 8 with sail in an ubuntu wsl2 container. The storage facade can read and write to the private folder without an issue.

When I run the same code above but with files from the public folder it works perfectly.

**Comment by jszobody** [comment]
Sounds like a permission issue, from your error message. I'm guessing this would also cause that error, give it a try:

```
$handle = fopen('/var/www/html/storage/app/private/1/backups/backup_955ef575-ba3f-42ee-a1da-4efaa87edca2/10414.pdf', 'r');
```

If PHP can't open a file, this package can't zip it.

**Comment by artjomzab** [comment]
Yep, same permission error. Setting proper permissions on the private folder solves this issue.
