### ISSUE TITLE
Enhancement: Comments to ZIP Files

### ISSUE THREAD

**Issue by safeboot** [stechstudio/laravel-zipstream#63]
Hello,

I'd like to see comments being able to be added to the ZIP files just to add a touch of customization. I don't have much to say so yeah. Comments!

**Comment by jszobody** [comment]
Sounds nice. I don't have time to add support for comments at the moment, but I'd be happy to review a Pull Request if you wanted to take a stab at it?

You would want to add a `setComment` method to the base `File` model, and have that call `setComment` method on the FileOptions class (see https://github.com/maennchen/ZipStream-PHP/blob/master/src/Option/File.php#L49).

I believe that would do it, from what I can see. Unless you want zip-level comments as well, which would need to be implemented in the ZipStream class.
