### ISSUE TITLE
Non-ASCII filenames are being transliterated to ASCII using Str::ascii in src/Models/File.php class

### ISSUE THREAD

**Issue by saeeddirect1** [stechstudio/laravel-zipstream#64]
Hi, @jszobody,

First of all, thank you so much for the great package. Always appreciate the hard work that you have put into it.

We have noticed that when creating zip, you are transliterating the filenames to ASCII using the Str::ascii method of Laravel's Str facade. So our file names that are in Arabic (non-ASCII characters) are transliterated to Ascii characters (which the Arabic speaking audience mostly don't understand)

We don't know the purpose behind it, perhaps you want to make the generated zip as much compatible as possible during extraction (since ZIPs don't carry encoding info with them).

I would like to know if it is possible to have this conversion optional e.g. in config files.

We would be grateful to make a PR if needed.

Method permalink: https://github.com/stechstudio/laravel-zipstream/blob/4f3cc7cb8c71a0c8d7ce739e0f833c7c967d1c05/src/Models/File.php#L105

```php
/**
     * @return string
     */
    public function getZipPath(): string
    {
        return Str::ascii(
            ltrim(
                preg_replace('|/{2,}|', '/',
                    $this->zipPath
                ),
                '/')
        );
    }
```

**Comment by jszobody** [comment]
@saeeddirect1 Take a look at #65? I think that should be what you are looking for. Test that out real quick to make sure? Then I'll merge and tag it.

**Comment by saeeddirect1** [comment]
Thanks for quick response,

That was more than perfect.

**Comment by jszobody** [comment]
4.7 was just tagged, you should be able to `composer update` and then set `ZIPSTREAM_FILE_SANITIZE=false` in your .env file.
