### ISSUE TITLE
bug: missing documentation and usage of AWS_USE_PATH_STYLE_ENDPOINT

### ISSUE THREAD

**Issue by andreacivita** [stechstudio/laravel-zipstream#69]
Hi! 
While using this package, I've noticed that this package is using `ZIPSTREAM_AWS_PATH_STYLE_ENDPOINT` (instead of default `AWS_USE_PATH_STYLE_ENDPOINT`)

Since no documentation is provided about this env key (even publishing config is not reported in `README.md`), it would be useful to allow dev to use default `AWS_USE_PATH_STYLE_ENDPOINT`.

**Comment by jszobody** [comment]
Merged, thanks.
