### ISSUE TITLE
Download from S3 fails if file has # in the name

### ISSUE THREAD

**Issue by albertmugisha** [stechstudio/laravel-zipstream#71]

**Comment by albertmugisha** [comment]
If you are zipping files from S3, if a source file has a # in the name, you get an error that file is not found

**Comment by jszobody** [comment]
Looks like AWS' own `S3UriParser` class won't correctly handle a filename with `#` in the name. And AWS [specifically mentions that you should avoid using that character](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) in object names.

Have you tried encoding that character? The `#` character is `%23` when URL encoded, you could attempt to encode your object names first. This is something that you should do before attempting to hand a filename with special characters to this package, or the AWS S3 client directly.
