### ISSUE TITLE
The name of the file being downloaded is “download” without extension

### ISSUE THREAD

**Issue by ingangelbaeza** [stechstudio/laravel-zipstream#82]
my code is the following:

```
 public function download()
    {
        $zip = Zip::create(\Str::random(20) . '.zip');
        foreach ($this->files as $file) {
            $zip->add('s3://bucket/' . $file['url'], $this->slug . '/' . $file['folder'] . '/' . $file['name']);
        }
        return $zip;
    }
```

if it downloads but the file is not formatted and is called "download" with no extension.

**Comment by jszobody** [comment]
I can't reproduce. That code you pasted just gave me a `OpI4O73yLqV92K4I5PRU.zip` download file.

Is that `download` method in your Controller? Not sure where `$this->files` is coming from, but I'm not thinking this is a controller method. 

Something else is getting in the way, and I would need to see the controller itself to help you further.

**Comment by lucdaalmeijer** [comment]
What was the solution for this? I'm having the same issue, This is my code:

    public function downloadDocumentsV2(int $year, string $type, Collection $documents = null)
    {
        if (is_null($documents)) {
            $documents = $this->getDocumentsForTypeGroupWithYear($year, $type)->get();
        }

        $zip = Zip::create('package.zip');

        foreach ($documents as $document) {
            $document = $document->files->first();
            $zip->add("s3://". config('filesystems.disks.s3.bucket') . '/' . $document->path, $document->name);
        }

        return $zip;
    }

**Comment by lucdaalmeijer** [comment]
or @jszobody if you have a solution for this 🙂

**Comment by lucdaalmeijer** [comment]
yes `downloadDocumentsV2`  this is being returned from an livewire component like this:

`return $this->entity->downloadDocumentsV2($this->year, $this->type);`

**Comment by jszobody** [comment]
That's your issue, you can't return a zip stream from a LiveWire component. LW wants to grab the entire response payload and serialize it inside its own JSON response, you lose all the benefits of streaming out the response (it doesn't start instantly) and LW gets in the way of the filename header.

https://github.com/stechstudio/laravel-zipstream/issues/34#issuecomment-830086993

https://github.com/stechstudio/laravel-zipstream/issues/34#issuecomment-1423545847

**Comment by lucdaalmeijer** [comment]
ohw i will look into that, thank you for the insight, response and the alternate approach!
