### ISSUE TITLE
ErrorException: fopen(): s3:// wrapper is disabled 

### ISSUE THREAD

**Issue by jehadassaf** [stechstudio/laravel-zipstream#88]
First of all, thanks for this awesome package and all your work on this!

Since #84 was merged it stopped working with `ErrorException: fopen(): s3:// wrapper is disabled in the server configuration by allow_url_fopen=0`

Using Laravel latest version.

My guess is the AWS S3 stream wrapper isn't getting registered correctly.
Any ideas on how to address this?

**Comment by jszobody** [comment]
According to that error message you need to enable `allow_url_fopen` in your php.ini file. 

If you cannot do that, I could look at providing the old S3 behavior via fallback somehow. The thing is, as explained in #84, the old behavior was not truly streaming the file in from S3 as I thought, and the new approach does. It's significantly faster, provided you have the ability to `allow_url_fopen` on your server.
