### ISSUE TITLE
Merge zip - source from s3

### ISSUE THREAD

**Issue by toriqsetiawan** [stechstudio/laravel-zipstream#99]
I have zip part on s3 directory 
`part1.z01, part2.z02, part3.z03`

I want to merge those files `full-part.zip`, and how can I achieve that process with this package?
thank you.

**Comment by jszobody** [comment]
This package is for creating a new zip from scratch, and immediately streaming it to the browser as it is being built. Merging zip parts is not something this package seeks to handle at all.
